### ISSUE TITLE
Small RNA analysis example using bcbio fails with ArrayIndexOutOfBounds error

### ISSUE THREAD

**Issue by sureman** [lpantano/seqbuster#19]
I tried to run your example analysis (http://seqcluster.readthedocs.org/example_pipeline.html) using your scripts for bcbio and the following error occurs:

[2016-01-11T19:19Z] Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 2
[2016-01-11T19:19Z]     at miraligner.map.alignment(map.java:476)
[2016-01-11T19:19Z]     at miraligner.map.align3end(map.java:441)
[2016-01-11T19:19Z]     at miraligner.map.align2(map.java:422)
[2016-01-11T19:19Z]     at miraligner.map.readseq(map.java:198)
[2016-01-11T19:19Z]     at miraligner.Main.main(Main.java:85)

The command from the bcbio debug log:

set -o pipefail; /usr/local/bin/miraligner -Xms750m -Xmx4500m -freq -sub 1 -trim 3 -add 3 -s hsa -i /data/bcbio/seqClusterExample/non_mirqc_bcbio/work/trimmed/serum_spiked_miRs_constant_repeat/SRR950893.clean.trimming.fastq -db /usr/local/share/bcbio/genomes/Hsapiens/hg19/srnaseq  -o /data/bcbio/seqClusterExample/non_mirqc_bcbio/work/mirbase/serum_spiked_miRs_constant_repeat/tx/tmps6dgts/serum_spiked_miRs_constant_repeat

I tried a subset of the input fastq and was able to re-create the error using the following fastq entry:

@seq_30_x4
TGACAGATTGAGAGCTCTTTC
+
IIHIHIIIIIHIHHIIHIIII

Any thoughts on how to overcome this error is greatly appreciated.

**Comment by lpantano** [comment]
Sorry about that. I see that the name of the input is weird, like missing dots. are u using the last version of bcbio?

i will try to reproduce with that sequence you send me tomorrow morning.(i just landed)

thanks for reporting the problem.

sent not from my computer

**Comment by sureman** [comment]
Thank you for your quick attention.  It seems that the dots were removed in the email.  I have tried both bcbio 0.9.5 and 0.9.6a with the same result.

Thanks again!

**Comment by lpantano** [comment]
Hi,

i am trying to reproduce with only a file with the sequence you sent me, 
but I don't get any errors.

/home/lpantano/soft/bcbiotools/bin/miraligner -Xms750m -Xmx2000m -freq 
-sub 1 -trim 3 -add 3 -s hsa -i test.fasq -db /home/lpantano/ 
soft/bcbio/genomes/Hsapiens/hg19/srnaseq -o test_out

That is the command. I guess you have all tools updated, so I am little 
confused.

Maybe you can send me a file you are having problems. miraligner is 
installed by bcbio using bioconda, is using that miraligner or maybe 
another? If you can find the miraligner.jar file and send I can try 
exactly what you are doing. It should be in the conda directory and then 
: share/java/seqbuster-2.3-2/

sorry about that. As well maybe you can try to update the data in bcbio.

hope we can find the problem.

**Comment by sureman** [comment]
Thank you again for the help.  I have packaged the miraligner script and jar from the bcbio folder, the database files, the full fastq file from which I pulled the previous sequence, and a script (miralignerTest.sh) to run the command as it was run in the bcbio pipeline in the attached tarball.  I ran the script with the included files and still receive the error.  Please let me know if you need anything further.

Thanks, Brad
[lpantano.tar.gz](https://github.com/lpantano/seqbuster/files/87390/lpantano.tar.gz)

**Comment by lpantano** [comment]
Hi!

i tried your files in the folder, but don't get any error. I had to 
change the command to this to use your jar file:

#!/bin/bash
./miraligner -Xms750m -Xmx2000m -freq -sub 1 -trim 3 -add 3 -s hsa -i 
SRR950893.clean.trimming.fastq -db ./ -o test_out

can be this an error. can you check if you have more than one miragliner 
command?

I assume you use linux and 64bits? which linux version?

let me know what happen if you use this command to make sure you use 
this jar file.

thanks for your patient.

**Comment by sureman** [comment]
Hi,

I made sure to target the miraligner file in the folder but I still get the same error.  I am running on 64bit Ubuntu 14.04 and java 1.8:

Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:        14.04
Codename:       trusty

java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)

It seems that there may be a dependency issue.

Thanks you for all of your help.

**Comment by lpantano** [comment]
oh! any chance to switch to java 1.7?

**Comment by sureman** [comment]
Looking at it right now:)  I'll keep you posted.

**Comment by sureman** [comment]
That's it!  So sorry for the bother.  I should have checked that early on.

Thanks again!  I'm looking forward to using your great tool.

**Comment by lpantano** [comment]
so nice!!!!!! yeah, the majority of tools in java in bcbio are for java 
1.7. Anyway will catch that error in case someone finds it as well!

thanks!!!!

**Comment by hmkim** [comment]
Thanks to @sureman, @lpantano 

This issue same for me.

```
$ java -version
openjdk version "1.8.0_45"
OpenJDK Runtime Environment (Zulu 8.7.0.5-linux64) (build 1.8.0_45-b14)
OpenJDK 64-Bit Server VM (Zulu 8.7.0.5-linux64) (build 25.45-b02, mixed mode)

$ /BiO/BioTools/bcbio/data/anaconda/bin/miraligner -Xms705m -Xmx4500m -sub 1 -trim 3 -add 3 -s hsa -i SRR950879_trimmed_trimmed.fastq -db /BiO/BioTools/bcbio/data/genomes/Hsapiens/hg19/srnaseq -o .
Format is not tabular,guessing fasta
species found
Go to mapping...
Mismatches: 1
Trimming: 3
Addition: 3
Species: hsa
Wed Jun 22 09:47:28 KST 2016

Reading reads
Number of reads to be mapped: 53980
Searching in precursors
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 8
        at miraligner.map.alignment(map.java:476)
        at miraligner.map.align2(map.java:405)
        at miraligner.map.readseq(map.java:198)
        at miraligner.Main.main(Main.java:85)

```

```
$ export PATH=/BiO/BioTools/bcbio/data/anaconda/bin:$PATH

$ java -version
openjdk version "1.7.0_91"
OpenJDK Runtime Environment (Zulu 7.12.0.3-linux64) (build 1.7.0_91-b15)
OpenJDK 64-Bit Server VM (Zulu 7.12.0.3-linux64) (build 24.91-b15, mixed mode)

$ /BiO/BioTools/bcbio/data/anaconda/bin/miraligner -Xms705m -Xmx4500m -sub 1 -trim 3 -add 3 -s hsa -i SRR950879_trimmed_trimmed.fastq -db /BiO/BioTools/bcbio/data/genomes/Hsapiens/hg19/srnaseq -o .
Format is not tabular,guessing fasta
species found
Go to mapping...
Mismatches: 1
Trimming: 3
Addition: 3
Species: hsa
Wed Jun 22 09:48:19 KST 2016

Reading reads
Number of reads to be mapped: 53980
Searching in precursors
Wed Jun 22 09:48:24 KST 2016
Num reads annotated: 11154
```

**Comment by lpantano** [comment]
yeah, it will work only in java 1.7 for now. I will migrate the annotation pipeline during summer to avoid java, and this will disappear hopefully.

thanks!

**Comment by sgmiriuka** [comment]
Hi Lorena, 

having troubles with miraligner, really wanted to use your isomiR....
I am getting this exception, I guess it is related to the use of Java 1.8. However, Java1.7 is no longer available. 

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 8
	at miraligner.map.alignment(map.java:476)
	at miraligner.map.align2(map.java:405)
	at miraligner.map.readseq(map.java:198)
	at miraligner.Main.main(Main.java:85)

Can you confirm me that mirnaligner is not running with 1.8? Any thoughts?

many thanks!!
santiago

**Comment by lpantano** [comment]
Hi,

Sorry about the issue. 

The last JAR file in the repo should be compatible with java 8.

https://github.com/lpantano/seqbuster/blob/miraligner/modules/miraligner/miraligner.jar?raw=true

Can you tell me if you are using directly the jar file or the conda executable?

If you already are using the file from the link above and you got it recently, can you try to do a small file, maybe first 100 lines and see if you can get the error and send me that file so I can test on my side?

Thanks

**Comment by sgmiriuka** [comment]
uf... not sure where I got the version I had... I downloaded in the last few days, not sure where i went wrong. 
Anyway, version on this link now works without problem!
thanks a lot!

**Comment by lpantano** [comment]
ok, glad it worked.

thanks!
