### ISSUE TITLE
miraligner gives zero annotated reads

### ISSUE THREAD

**Issue by palbioinfor** [lpantano/seqbuster#20]
Hi
I am new to isomiR analysis and I tried using miraligner with fastq sequences. I have couple of issues-

1. When I run my script-
java -jar miraligner.jar -sub 1 -trim 3 -add 3 -s hsa -i /Users/pg2597/Downloads/pilot_fastq/xyz.fastq -db DB -o /Users/pg2597/Desktop/output
 I get this while process-
  'Format is not tabular,guessing fasta '  
I checked the format of fastq files still it's taking it as a fasta plus what does it mean by Format is not tabular.

2. As result I get-

species found
Go to mapping...
Mismatches: 1
Trimming: 3
Addition: 3
Species: hsa
Tue May 29 20:07:44 EDT 2018

Reading reads
Number of reads to be mapped: 1086336
Searching in precursors
Tue May 29 20:07:48 EDT 2018
Num reads annotated: 0

As can be seen that reads are not annotated. I get a blank output file only with header info not single sequence annotation. Can someone explain this?

I need to find isomiRs in my data.

**Comment by lpantano** [comment]
Hi,

Thanks for trying the tool. 

That is just a message.

Can I ask you if you have trimmed your data already?

The typical steps before that are described here:

http://seqcluster.readthedocs.io/mirna_annotation.html <http://seqcluster.readthedocs.io/mirna_annotation.html>

For the number I am seeing there, I think this is just the raw fastq file, right?

Let me know if doing the previous steps explained in the link before changes the output of this or not.

Cheers

**Comment by palbioinfor** [comment]
Yes, 
I was picking wrong input file. It worked with right ones. Sorry it was my bad.
